builds:
  - binary: latitude55-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: latitude55-cli
    homepage: https://github.com/hloughrey/latitude55-cli
    commit_author:
      name: "Hugh Loughrey"
      email: "hugh.loughrey@gmail.com"

checksum:
  name_template: "checksums.txt"
